// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi2KGuuMvGGNxd3kX5Ankae7x9GO9yEbA"',
    appId: '1:423905578853:android:553ee38c39b2743dbf1b8c"',
    messagingSenderId: '423905578853',
    projectId: 'nike-fbbd4',
    databaseURL: 'https://nike-fbbd4-default-rtdb.firebaseio.com',
    storageBucket: 'nike-fbbd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1LwBZHA90XLe7d-g8SGk-nM4ooFbjNk',
    appId: '1:423905578853:ios:c270e01ee3d9420ebf1b8c',
    messagingSenderId: '423905578853',
    projectId: 'nike-fbbd4',
    databaseURL: 'https://nike-fbbd4-default-rtdb.firebaseio.com',
    storageBucket: 'nike-fbbd4.appspot.com',
    iosClientId: '423905578853-ig00joadalpuogp9174cvd8bqbku4ibu.apps.googleusercontent.com',
    iosBundleId: 'com.htnguyen.nike.nike',
  );

}
